### ISSUE TITLE
Rstudio's network is unstable when downloading tiff files, What can be done about it?

### ISSUE THREAD

**Issue by freshmanMrxin** [zecojls/downloadSoilGridsV2#2]
trying URL 'https://maps.isric.org/mapserv?map=/map/cec.map&SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=cec_5-15cm_mean&FORMAT=image/tiff&SUBSET=long(114.99,125.01)&SUBSET=lat(34.99,45.01)&SUBSETTINGCRS=http://www.opengis.net/def/crs/EPSG/0/4326'
downloaded 624 KB

Error in download.file(wcs, destfile = destination.file, mode = "wb") : 
  download from 'https://maps.isric.org/mapserv?map=/map/cec.map&SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=cec_5-15cm_mean&FORMAT=image/tiff&SUBSET=long(114.99,125.01)&SUBSET=lat(34.99,45.01)&SUBSETTINGCRS=http://www.opengis.net/def/crs/EPSG/0/4326' failed
In addition: Warning message:
In download.file(wcs, destfile = destination.file, mode = "wb") :
  URL 'https://maps.isric.org/mapserv?map=/map/cec.map&SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=cec_5-15cm_mean&FORMAT=image/tiff&SUBSET=long(114.99,125.01)&SUBSET=lat(34.99,45.01)&SUBSETTINGCRS=http://www.opengis.net/def/crs/EPSG/0/4326': Timeout of 60 seconds was reached
The above content is R error reporting.

**Comment by quinncampbell0** [comment]
Hey there, I was getting the same timeout error. You can fix this by setting a longer timeout using options(), and setting the value to more than 60 seconds. Download speeds are pretty slow, I think it is WCS that only allows a certain download speed? Only averaging around 1 Mbps, so it is going to take ages to download all this data. 
`options(timeout=240)`

**Comment by freshmanMrxin** [comment]
> Hey there, I was getting the same timeout error. You can fix this by setting a longer timeout using options(), and setting the value to more than 60 seconds. Download speeds are pretty slow, I think it is WCS that only allows a certain download speed? Only averaging around 1 Mbps, so it is going to take ages to download all this data. `options(timeout=240)`

Thank you for your answer, the method （options(timeout=240)）you provided I tried and so far it is working.
