### ISSUE TITLE
Get the rasters over the whole globe to combine them into one

### ISSUE THREAD

**Issue by tristanubaldi** [zecojls/downloadSoilGridsV2#3]
Hello, I need your help because I am trying to use your script to download each soil variable and get the .tiff files that will cover the whole globe, and then combine them into one global tiff file.

I am trying to put 
```
min.long <- -180
min.lat <- -90
max.long <- 180
max.lat <- 90
```
but it does not work, and I have no idea what to do.
Do you know how I can do this?

**Comment by zecojls** [comment]
Hi @tristanubaldi,

Unfortunately, the method I describe in the R scripts has a limited downloading capacity imposed by SoilGrids. You can download smaller regions/tiles that span over 10 degrees of Latitude and Longitude. Therefore you need to create a shapefile containing these smaller bounding boxes as described in [script_making_tile_indices.R](https://github.com/zecojls/downloadSoilGridsV2/blob/master/script_making_tile_indices.R), iterate/loop over them to download the smaller pieces ([script_soilGrids_download.R](https://github.com/zecojls/downloadSoilGridsV2/blob/master/script_soilGrids_download.R)), and finally, bind everything together using GDAL ([script_overviews_and_virtual_rasters.R](https://github.com/zecojls/downloadSoilGridsV2/blob/master/script_overviews_and_virtual_rasters.R)).

You can try to download the full global data using other methods, like exporting from Google Earth Engine:
https://www.isric.org/news/soilgrids-data-now-available-google-earth-engine
